import { mkdir, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import { join } from "node:path";
import type { MigrationContext } from "../types.js";
import type { UiBus } from "../tui/bus.js";
import { buildWpEnvConfig, wpEnvStart, writeWpEnvConfig } from "../wp/wpEnv.js";

export async function runBoot(ctx: MigrationContext, bus: UiBus): Promise<void> {
  bus.pushStreamEvent("boot", { type: "phase_start", phase: "boot", message: "preparing wp-env" });
  const detected = ctx.detected;
  if (!detected) throw new Error("detect phase must run before boot");

  await mkdir(ctx.themeDir, { recursive: true });
  await mkdir(ctx.pluginDir, { recursive: true });

  const styleCssPath = join(ctx.themeDir, "style.css");
  if (!existsSync(styleCssPath)) {
    await writeFile(
      styleCssPath,
      `/*\nTheme Name: ${detected.siteTitle ?? detected.themeSlug}\nTheme URI: https://example.com\nDescription: Generated by to-wordpress. Placeholder until Theme phase completes.\nVersion: 0.1.0\nText Domain: ${detected.themeSlug}\n*/\n`,
      "utf8",
    );
  }
  const indexPhpPath = join(ctx.themeDir, "index.php");
  if (!existsSync(indexPhpPath)) {
    await writeFile(indexPhpPath, "<?php\n// placeholder — replaced by Theme phase\n", "utf8");
  }

  const pluginMainPath = join(ctx.pluginDir, `${detected.pluginSlug}.php`);
  if (!existsSync(pluginMainPath)) {
    await writeFile(
      pluginMainPath,
      `<?php\n/**\n * Plugin Name: ${detected.pluginSlug}\n * Description: Site-specific plugin generated by to-wordpress. Placeholder.\n * Version: 0.1.0\n * License: GPL-2.0-or-later\n * Text Domain: ${detected.pluginSlug}\n */\nif (!defined('ABSPATH')) { exit; }\n`,
      "utf8",
    );
  }

  await mkdir(ctx.workDir, { recursive: true });
  const config = buildWpEnvConfig({
    sourceDir: ctx.sourceDir,
    themeDir: ctx.themeDir,
    pluginDir: ctx.pluginDir,
    workDir: ctx.workDir,
    siteTitle: detected.siteTitle,
  });
  await writeWpEnvConfig(ctx.wpEnvConfigPath, config);
  bus.pushStreamEvent("boot", { type: "info", phase: "boot", message: `wrote ${ctx.wpEnvConfigPath}` });

  bus.pushStreamEvent("boot", { type: "info", phase: "boot", message: "starting wp-env (pulls Docker images on first run, can take several minutes)" });
  const exit = await wpEnvStart({
    cwd: ctx.sourceDir,
    onLine: (line, stream) => {
      if (stream === "stderr") {
        bus.pushStreamEvent("boot", { type: "stderr", line });
      } else {
        bus.pushStreamEvent("boot", { type: "info", phase: "boot", message: line });
      }
    },
    timeoutMs: 30 * 60 * 1000,
  });
  if (exit !== 0) {
    bus.pushStreamEvent("boot", { type: "phase_fail", phase: "boot", message: `wp-env start exited with ${exit}` });
    throw new Error(`wp-env start failed (${exit})`);
  }
  ctx.wpUrl = `http://localhost:${(config.port as number) ?? 8888}`;
  bus.pushStreamEvent("boot", { type: "info", phase: "boot", message: `wp-env up at ${ctx.wpUrl}` });
  bus.pushStreamEvent("boot", { type: "phase_ok", phase: "boot" });
}
